### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by agarzon** [jayanam/batex#11]
`
Traceback (most recent call last):
  File "C:\Users\Alexander\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\Alexander\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\batex-master\bex_export.py", line 77, in do_export
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1

`

**Comment by drtyrell969** [comment]
I have the exact issue.

**Comment by NoriteSC** [comment]
use full windows path example C:\Users\%username%\Desktop\

**Comment by jayanam** [comment]
Relative path is now converted to absoolute path
