### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Tamzel** [jayanam/batex#4]
Traceback (most recent call last):

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\addons\batex-master\bex_op.py", line 16, in execute

    bat_export.do_export()

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\addons\batex-master\bex_export.py", line 46, in do_export

    path_mode='ABSOLUTE')

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\modules\bpy\ops.py", line 201, in _call_

    ret = op_call(self.idname_py(), None, kw)

RuntimeError: Error: Traceback (most recent call last):

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\addons\io_scene_fbx\__init__.py", line 552, in execute

    return export_fbx_bin.save(self, context, **keywords)

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3118, in save

    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3027, in save_single

    encode_bin.write(filepath, root, FBX_VERSION)

  File "C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write

    with open(fn, 'wb') as f:

FileNotFoundError: [Errno 2] No such file or directory: '//..\\Downloads\\Kitbash Mini Cyberpunk\\/TowerC_RoofTar.fbx'

location: C:\Users\Allan\Desktop\ALLAN_blender-2.80-windows64\2.80\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

**Comment by Nohka** [comment]
I get the same error and what I am instantly confused about is the use of slashes in the filepath.
You have a backwards and a forwards slash in a row before the filename, whereas I had two backwards slashes and one forward slash before the filename. Not sure, how this works code-wise, but just sharing it out there.

**Comment by jayanam** [comment]
Which Blender version are u using?

**Comment by Nohka** [comment]
2.82.7

**Comment by jayanam** [comment]
Ok, folder is now converted to abspath,
