### ISSUE TITLE
i can't export 

### ISSUE THREAD

**Issue by mostafahaykol** [jayanam/batex#8]
hey!! here is the issue that i have when i try to export it using the addon
bpy.context.space_data.params.directory = "E:\\Blender projects\\"
Modules Installed () from 'E:\\Blender projects\\addons\\batex-master.zip' into 'C:\\Users\\aboha\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = "bate"
Modules Installed (batex-master) from 'E:\\Blender projects\\addons\\batex-master.zip' into 'C:\\Users\\aboha\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
bpy.context.space_data.params.directory = "E:\\Blender projects\\models\\pendant light\\"
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.bex_ot_operator()
Exported to 
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.bex_ot_openfolder()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.014.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.016.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.016.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.bex_ot_openfolder()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.016.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.bex_ot_operator()
Traceback (most recent call last):
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\aboha\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\batex-master\bex_export.py", line 102, in do_export
    path_mode='ABSOLUTE')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\__init__.py", line 635, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '///Bulb.016.fbx'

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

**Comment by jayanam** [comment]
Why you closed the issue?
